### ISSUE TITLE
feat: Basic Flutter Code Files

### ISSUE THREAD

**Issue by raghavSharma1472** [raghavSharma1472/RecipeBookFlutter#1]
Try to push a newly made flutter code in the repo. You may delete the default code provided by flutter.

**Comment by littleironical** [comment]
I can do this. Should I give `FlutterRecipeBook` as the app name?

**Comment by raghavSharma1472** [comment]
> I can do this. Should I give `FlutterRecipeBook` as the app name?

That is completely your decision, for remembrance you might put the same name but if you don't want to its fine it doesn't matter until and unless you push that code in this repository.

**Comment by littleironical** [comment]
Do review the pull request #4
