### ISSUE TITLE
feat: ListViews

### ISSUE THREAD

**Issue by raghavSharma1472** [raghavSharma1472/RecipeBookFlutter#3]
Try to build the UI of the first page using **ListViews**. Adjust the Scrollable physics and place the search bar at the top. We have to have an App Bar in the App so should account for that. Be Innovative

**Comment by littleironical** [comment]
What should be there in those lists?

**Comment by raghavSharma1472** [comment]
> What should be there in those lists?

In the final version we would like to have an image, Recipe name and rating to display and will be getting that data from the API, but for now you can leave it to be a empty or include some dummy code with a 'for' loop

**Comment by riturajjain2000** [comment]
Can I work on this ??

**Comment by raghavSharma1472** [comment]
Sure @riturajjain2000

**Comment by riturajjain2000** [comment]
can you assign this to me @raghavSharma1472?
