### ISSUE TITLE
feat: Splash Screen

### ISSUE THREAD

**Issue by raghavSharma1472** [raghavSharma1472/RecipeBookFlutter#7]
We can Create a Splash Screen (Screen shown for 4-5 sec while opening an app), it can be just an image reflecting what's inside the app, could also have some animation if you want it to look fancy.

**Comment by littleironical** [comment]
Or we could just show the icon of the app and loading for a few seconds.

**Comment by raghavSharma1472** [comment]
Loading wont be a good options, its actually a page where a person won't mind staring at and is actually short for eg: if you open YouTube app you will see immediately after opening, the logo is displayed for few seconds and then the main screen is loaded, that screen is splash screen.

**Comment by littleironical** [comment]
> if you open YouTube app you will see immediately after opening, the logo is displayed for few seconds and then the main screen is loaded, that screen is splash screen.

Yes, so we can do this like in YouTube. User will see the logo for 1 or 1.5 seconds.

But first we need to have a logo for this app.

**Comment by raghavSharma1472** [comment]
Yeah, any logo you find on internet related to the app concept is fine, its just for learning
