### ISSUE TITLE
feat: Display Dishes

### ISSUE THREAD

**Issue by raghavSharma1472** [raghavSharma1472/RecipeBookFlutter#9]
Here we will display 10 dishes in the first page with image, name and rating. Just have to link the class of Data converted with the list views, taking care of the geometry of containers in the list.

**Comment by littleironical** [comment]
Those 10 dishes can be anything, right?

**Comment by raghavSharma1472** [comment]
Yes they could be anything in the API data you receive

**Comment by riturajjain2000** [comment]
I would like to work on this issue !

**Comment by priyanshu029** [comment]
I can assign me to it . I can do it
